spring:
  application:
    name: helpdesk-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/helpdesk}
    username: ${DB_USERNAME:helpdesk}
    password: ${DB_PASSWORD:helpdesk}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  config:
    import: "optional:file:.env[.properties]"

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}